Green/Models/AnnualR.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Green.Models
{
    public class AnnualR
    {

        [Key]
        public int ID { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }
        public string Year { get; set; }
        public byte[] file { get; set; }
        [Display(Name = "Details")]
        public string location { get; set; }
    }
}

Green/Controllers/AnnualRsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Green.Models;
using System.IO;
namespace Green.Controllers
{
    public class AnnualRsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AnnualRs
        public ActionResult Index()
        {
            return View(db.AnnualRs.ToList());
        }

        // GET: AnnualRs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnualR annualR = db.AnnualRs.Find(id);
            if (annualR == null)
            {
                return HttpNotFound();
            }
            return View(annualR);
        }

        // GET: AnnualRs/Create
        public ActionResult Create()
        {
            return View();
        }
        public byte[] ConvertToBytes(HttpPostedFileBase files)
        {

            BinaryReader reader = new BinaryReader(files.InputStream);
            return reader.ReadBytes(files.ContentLength);
        }

        // POST: AnnualRs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Year,file,location")] AnnualR annualR, HttpPostedFileBase files)
        {

            if (files != null && files.ContentLength > 0)
            {
                annualR.location = files.FileName;
                string[] bits = annualR.location.Split('\\');

                annualR.file = ConvertToBytes(files);

            }
            if (ModelState.IsValid)
            {
                db.AnnualRs.Add(annualR);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(annualR);
        }
        public ActionResult Download(int? id)
        {

            MemoryStream ms = null;

            var item = db.AnnualRs.FirstOrDefault(x => x.ID == id);
            if (item != null)
            {
                ms = new MemoryStream(item.file);
            }
            return new FileStreamResult(ms, item.location);


            //return RedirectToAction("Download");
        }

        [HttpPost]
        public ActionResult ViewPDF(int? id)
        {
            var r = db.AnnualRs.Find(id);
            //PDF pDF = db.PDFs.Find(id);
            string embed = "<object data=\"{0}\" type=\"application/pdf\" width=\"500px\" height=\"300px\">";
            embed += "If you are unable to view file, you can download from <a href = \"{0}\">here</a>";
            embed += " or download <a target = \"_blank\" href = \"http://get.adobe.com/reader/\">Adobe PDF Reader</a> to view the file.";
            embed += "</object>";
            TempData["Embed"] = string.Format(embed, VirtualPathUtility.ToAbsolute(r.location));

            return RedirectToAction("Index");
        }


        // GET: AnnualRs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnualR annualR = db.AnnualRs.Find(id);
            if (annualR == null)
            {
                return HttpNotFound();
            }
            return View(annualR);
        }

        // POST: AnnualRs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Year,file,location")] AnnualR annualR)
        {
            if (ModelState.IsValid)
            {
                db.Entry(annualR).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(annualR);
        }

        // GET: AnnualRs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnualR annualR = db.AnnualRs.Find(id);
            if (annualR == null)
            {
                return HttpNotFound();
            }
            return View(annualR);
        }

        // POST: AnnualRs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AnnualR annualR = db.AnnualRs.Find(id);
            db.AnnualRs.Remove(annualR);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Green/Views/AnnualRs/Create.cshtml
@model Green.Models.AnnualR

@{
    ViewBag.Title = "";
}
<center>
    <h2>
        <b>
            <i>

                <font color="red">Annual Report:</font>
            </i>

        </b>

    </h2>
</center>

@using (Html.BeginForm("Create", "AnnualRs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-5">

                <input type="file" name="files" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Green/Views/AnnualRs/Delete.cshtml
@model Green.Models.AnnualR

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnnualR</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Green/Views/AnnualRs/Details.cshtml
@model Green.Models.AnnualR

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AnnualR</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Green/Views/AnnualRs/Download.cshtml
@model Green.Models.AnnualR

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("ViewPDF", "Home", FormMethod.Post))
    {
        <a href="javascript:;" onclick="document.forms[0].submit();">View PDF</a>
        <hr />
        @Html.Raw(TempData["Embed"])
    }
</body>
</html>

Green/Views/AnnualRs/Edit.cshtml
@model Green.Models.AnnualR

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AnnualR</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Green/Views/AnnualRs/Index.cshtml
@model IEnumerable<Green.Models.AnnualR>

@{
    ViewBag.Title = "";
}
<center>
    <h2>
        <b>
            <i>

                <font color="red">Annual Reports:</font>
            </i>

        </b>

    </h2>
</center>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.location)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Year)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.location)
        </td>
        <td>
            <a href="@Url.Action("Download","AnnualRs", new { id=item.ID })" rel="tooltip" title="Download" class="btn btn-success btn-simple btn-xs"><i class="fa fa-download">Download</i></a>

         
        </td>
    </tr>
}

</table>

Green/Views/AnnualRs/ViewPDF.cshtml
@model Green.Models.AnnualR
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("ViewPDF", "Home", FormMethod.Post))
    {
        <a href="javascript:;" onclick="document.forms[0].submit();">View PDF</a>
        <hr />
        @Html.Raw(TempData["Embed"])
    }
</body>
</html>