Green/Controllers/VaccanciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Green.Models;
using System.IO;


namespace Green.Controllers
{
    public class VaccanciesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Vaccancies
        public ActionResult Index()
        {
            return View(db.Vaccancies.ToList());
        }

        // GET: Vaccancies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaccancie vaccancie = db.Vaccancies.Find(id);
            if (vaccancie == null)
            {
                return HttpNotFound();
            }
            return View(vaccancie);
        }

        // GET: Vaccancies/Create
        public ActionResult Create()
        {
            return View();
        }

        public byte[] ConvertToBytes(HttpPostedFileBase files)
        {

            BinaryReader reader = new BinaryReader(files.InputStream);
            return reader.ReadBytes(files.ContentLength);
        }
        // POST: Vaccancies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Units,Position,ClosingDate,file,location")] Vaccancie vaccancie, HttpPostedFileBase files)
        {
            if (files != null && files.ContentLength > 0)
            {
                vaccancie.location = files.FileName;
                string[] bits = vaccancie.location.Split('\\');

                vaccancie.file = ConvertToBytes(files);

            }

            if (ModelState.IsValid)
            {
                db.Vaccancies.Add(vaccancie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vaccancie);
        }

        public ActionResult Downld(int? id)
        {

            MemoryStream ms = null;

            var item = db.Vaccancies.FirstOrDefault(x => x.ID == id);
            if (item != null)
            {
                ms = new MemoryStream(item.file);
            }
            return new FileStreamResult(ms, item.location);


            //return RedirectToAction("Download");
        }

        [HttpPost]
        public ActionResult ViewFile(int? id)
        {
            var r = db.Vaccancies.Find(id);
            //PDF pDF = db.PDFs.Find(id);
            string embed = "<object data=\"{0}\" type=\"application/pdf\" width=\"500px\" height=\"300px\">";
            embed += "If you are unable to view file, you can download from <a href = \"{0}\">here</a>";
            embed += " or download <a target = \"_blank\" href = \"http://get.adobe.com/reader/\">Adobe PDF Reader</a> to view the file.";
            embed += "</object>";
            TempData["Embed"] = string.Format(embed, VirtualPathUtility.ToAbsolute(r.location));

            return RedirectToAction("Index");
        }



        // GET: Vaccancies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaccancie vaccancie = db.Vaccancies.Find(id);
            if (vaccancie == null)
            {
                return HttpNotFound();
            }
            return View(vaccancie);
        }

        // POST: Vaccancies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Units,Position,ClosingDate,file,location")] Vaccancie vaccancie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vaccancie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vaccancie);
        }

        // GET: Vaccancies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaccancie vaccancie = db.Vaccancies.Find(id);
            if (vaccancie == null)
            {
                return HttpNotFound();
            }
            return View(vaccancie);
        }

        // POST: Vaccancies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vaccancie vaccancie = db.Vaccancies.Find(id);
            db.Vaccancies.Remove(vaccancie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Green/Views/Vaccancies/Create.cshtml
@model Green.Models.Vaccancie

@{
    ViewBag.Title = "";
}
<center>
    <h2>
        <b>
            <i>

                <font color="red">Vaccancies Forms:</font>
            </i>
          
        </b>

    </h2>
</center>

@using (Html.BeginForm("Create", "Vaccancies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Units, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Units, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Units, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClosingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClosingDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-5">
               
                <input type="file" name="files" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Green/Views/Vaccancies/Delete.cshtml
@model Green.Models.Vaccancie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vaccancie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Units)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Units)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClosingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClosingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Green/Views/Vaccancies/Details.cshtml
@model Green.Models.Vaccancie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vaccancie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Units)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Units)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClosingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClosingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Green/Views/Vaccancies/Downld.cshtml
@model Green.Models.Vaccancie

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("ViewFile", "Home", FormMethod.Post))
    {
        <a href="javascript:;" onclick="document.forms[0].submit();">View PDF</a>
        <hr />
        @Html.Raw(TempData["Embed"])
    }
</body>
</html>

Green/Views/Vaccancies/Edit.cshtml
@model Green.Models.Vaccancie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vaccancie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Units, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Units, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Units, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClosingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClosingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Green/Views/Vaccancies/Index.cshtml
@model IEnumerable<Green.Models.Vaccancie>

@{
    ViewBag.Title = "";
}
<center>
    <h2>
        <b>
            <i>

                <font color="red">Vaccancies Forms:</font>
            </i>

        </b>

    </h2>
</center>


<div class="container">

    <div class="form-group">

        <div class="input-group">

            <span class="input-group-addon">
                <i class="glyphicon glyphicon-search"></i>
            </span>
            <input type="text" id="Search" placeholder="Search" class="form-control" />

        </div>
    </div>
</div>



<table class="table table-striped">
    <thead>
        <tr>
            <th> Units</th>
            <th> Position</th>
            <th> Closing Date</th>
            <th> Details</th>


        </tr>
    </thead>

    <tbody>

        @foreach (var Item in Model)
        {
            <tr class="Search">
                <td>
                    @Item.Units
                </td>
                <td>
                    @Item.Position
                </td>
                <td>
                    @Item.ClosingDate
                </td>

                <td>
                    @Item.location
                </td>

                <td>

                    <a href="@Url.Action("Downld","Vaccancies", new { id=Item.ID })" rel="tooltip" title="Download" class="btn btn-success btn-simple btn-xs"><i class="fa fa-download">Download</i></a>



                </td>
            </tr>
        }


    </tbody>
</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
            $(document).ready(function () {
                function Contains(text_one, text_two) {
                    if (text_one.indexOf(text_two) != -1)
                        return true;
                }
                $("#Search").keyup(function () {
                    var searchText = $("#Search").val().toLowerCase();
                    $(".Search").each(function () {
                        if (!Contains($(this).text().toLowerCase(), searchText)) {
                            $(this).hide();
                        }
                        else {
                            $(this).show();
                        }
                    })
                }
                )
            }
            )
            var SendEmail = function () {

                $.ajax({
                    type: "Post",
                    url: "/Students/SendMailToUser",
                    success: function (data) {
                        alert("Sucess")
                    }


                })

            }
</script>

Green/Views/Vaccancies/ViewFile.cshtml
@model Green.Models.Vaccancie
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("ViewFile", "Home", FormMethod.Post))
    {
        <a href="javascript:;" onclick="document.forms[0].submit();">View PDF</a>
        <hr />
        @Html.Raw(TempData["Embed"])
    }
</body>
</html>